apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: go-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-sample
  template:
    metadata:
      labels:
        app: go-sample
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: my-container
          image: harbor.133.186.210.147.nip.io/cp-test/go-sample:latest
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault