name: Build, Push, and Scan with Trivy in Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure Docker daemon for SSL
      run: |
        sudo mkdir -p /etc/docker/certs.d/harbor.133.186.210.147.nip.io
        echo "${{ secrets.HARBOR_CA }}" | sudo tee /etc/docker/certs.d/harbor.133.186.210.147.nip.io/ca.crt

    - name: Log in to Harbor
      env:
        HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login harbor.133.186.210.147.nip.io -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      env:
        IMAGE_NAME: harbor.133.186.210.147.nip.io/cp-portal/go-sample:latest
      run: |
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy

    - name: Scan Docker image with Trivy
      env:
        IMAGE_NAME: harbor.133.186.210.147.nip.io/cp-portal/go-sample:latest
      run: |
        trivy image --exit-code 1 --severity HIGH,CRITICAL $IMAGE_NAME

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl set image deployment/my-deployment my-container=$IMAGE_NAME
        kubectl rollout status deployment/my-deployment
